app.py
import os
from flask import Flask
from routes import pages
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()


def create_app():
    app = Flask(__name__)
    client = MongoClient(os.environ.get("MONGODB_URI"))
    app.db = client.get_default_database()

    app.register_blueprint(pages)
    return app

routes.py
from flask import current_app, Blueprint, render_template, request, redirect, url_for
import datetime
import uuid

pages = Blueprint("habits", __name__, template_folder="templates", static_folder="static")


@pages.context_processor
def add_calc_date_range():
    def date_range(start: datetime.datetime):
        dates = [start + datetime.timedelta(days=diff) for diff in range(-3, 4)]
        return dates

    return {"date_range": date_range}


def at_midnight(date_obj):
    return datetime.datetime(date_obj.year, date_obj.month, date_obj.day)


def get_selected_date(date_str):
    if date_str:
        selected_date = at_midnight(datetime.datetime.fromisoformat(date_str))
    else:
        selected_date = at_midnight(datetime.datetime.today())
    return selected_date


@pages.route("/")
def index():
    date_str = request.args.get("date")
    selected_date = get_selected_date(date_str)

    habits_on_date = current_app.db.habits.find({"added": {"$lte": selected_date}})
    completions = [
        habit["habit"]
        for habit in current_app.db.completions.find({"date": selected_date})
    ]

    return render_template(
        "index.html",
        habits=habits_on_date,
        title="Habit Tracker - Home",
        selected_date=selected_date,
        completions=completions
    )


@pages.route("/add", methods=["GET", "POST"])
def add_habit():
    date_str = request.args.get("date")
    selected_date = get_selected_date(date_str)

    if request.method == "POST":
        current_app.db.habits.insert_one(
            {"_id": uuid.uuid4().hex, "added": selected_date, "name": request.form.get("habit")}
        )

    return render_template(
        "add_habit.html",
        title="Habit Tracker - Add Habit",
        selected_date=selected_date
    )


@pages.route("/complete", methods=["POST"])
def complete():
    date_str = request.form.get("date")
    habit = request.form.get("habitId")
    date = at_midnight(datetime.datetime.fromisoformat(date_str))
    current_app.db.completions.insert_one({"date": date, "habit": habit})

    return redirect(url_for("habits.index", date=date_str))


@pages.route("/delete", methods=["GET", "POST"])
def delete_habit():
    date_str = request.args.get("date")
    habit_id = request.form.get("habitId")

    if request.method == "POST":
        current_app.db.habits.delete_many({"_id": habit_id})

    return redirect(url_for("habits.index", date=date_str))

templates/add_habit.html
{% extends "layout.html" %}

{% block main_content %}
    <form class="form" method="POST">
        <textarea class="form__input" id="habit" name="habit" rows="3" placeholder="Add a new daily habit"></textarea>
        <button class="form__button" type="submit">Add</button>
    </form>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block main_content %}
    <section class="habit-list">
        {% for habit in habits %}
            <div class="habit-row">
                {% set completed = habit["_id"] in completions %}
                {% if completed %}
                    <div class="habit completed">
                        <p class="habit__name">
                            {{ habit["name"] }}
                        </p>
                        <svg class="habit__icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                        </svg>
                    </div>
                {% else %}
                    <div class="habit">
                        <form class="habit__form" method="POST" action="{{ url_for('habits.complete') }}">
                            <input type="hidden" name="habitId" value="{{ habit['_id'] }}" />
                            <input type="hidden" name="date" value="{{ selected_date }}" />
                            <button type="submit" class="habit__button">
                                {{ habit["name"] }}
                            </button>
                        </form>
                    </div>
                {% endif %}
                <div class="habit-delete">
                    <form class="habit__form" method="POST" action="{{ url_for('habits.delete_habit') }}">
                        <input type="hidden" name="habitId" value="{{ habit['_id'] }}" />
                        <button type="submit" class="habit__button-del">
                            <svg class="habit__icon-del" viewBox="0 0 20 20">
                                <path fill="currentColor" d="M10.185,1.417c-4.741,0-8.583,3.842-8.583,8.583c0,4.74,3.842,8.582,8.583,8.582S18.768,14.74,18.768,10C18.768,5.259,14.926,1.417,10.185,1.417 M10.185,17.68c-4.235,0-7.679-3.445-7.679-7.68c0-4.235,3.444-7.679,7.679-7.679S17.864,5.765,17.864,10C17.864,14.234,14.42,17.68,10.185,17.68 M10.824,10l2.842-2.844c0.178-0.176,0.178-0.46,0-0.637c-0.177-0.178-0.461-0.178-0.637,0l-2.844,2.841L7.341,6.52c-0.176-0.178-0.46-0.178-0.637,0c-0.178,0.176-0.178,0.461,0,0.637L9.546,10l-2.841,2.844c-0.178,0.176-0.178,0.461,0,0.637c0.178,0.178,0.459,0.178,0.637,0l2.844-2.841l2.844,2.841c0.178,0.178,0.459,0.178,0.637,0c0.178-0.176,0.178-0.461,0-0.637L10.824,10z"></path>
                            </svg>
                        </button>
                    </form>
                </div>
            </div>
        {% endfor %}
    </section>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{{ title }}</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}">

    {% block head_content %}{% endblock %}
</head>
<body>
    <header class="header">
        <h1 class="header__logo">
            <a href="{{ url_for('habits.index') }}" class="header__link"> Habits </a>
        </h1>
        {% if "add" not in request.endpoint %}
            <a href="{{ url_for('habits.add_habit') }}" class="header__link"> + Add new </a>
        {% endif %}
    </header>
    <main class="main">
        <section class="dates">
            {% for date in date_range(selected_date) %}
                {% if "add" in request.endpoint %}
                    {% set href_dates = url_for('habits.add_habit', date=date) %}
                {% else %}
                    {% set href_dates = url_for('habits.index', date=date) %}
                {% endif %}
                <a
                   class="dates__link {{ 'dates__link--current' if loop.index0 == 3 else '' }}"
                   href="{{ href_dates }}"
                >
                    <time class="date" datetime="{{ date }}">
                        <span>{{ date.strftime("%a") }}</span>
                        <span>{{ date.strftime("%d") }}</span>
                    </time>
                </a>
            {% endfor %}
        </section>
        {% block main_content %}{% endblock %}
    </main>
</body>

</html>